python bindings for abm
DLR-SC/memilio pull request #258
Opened 2022-04-26 15:26 UTC by dabele

##Changes

* python bindings for ABM
* unit tests
* some small ABM bugfixes

## Merge Request - GuideLine Checklist 

**Guideline** to check code before resolve WIP and approval, respectively.
As many checkboxes as possible should be ticked.

### Checks by code author:
* [x] There is at least one issue associated with the pull request.
* [x] The branch follows the naming conventions as defined in the [git workflow](git-workflow).
* [x] New code adheres with the [coding guidelines](coding-guidelines)
* [x] Tests for new functionality has been added
* [x] A local test was succesful
* [x] There is appropriate **documentation** of your work. (use doxygen style comments)
* [ ] If new third party software is used, did you pay attention to its license? Please remember to add it to the wiki after successful merging.
* [ ] If new mathematical methods or epidemiological terms are used, has the glossary been updated ? Did you provide further documentation ?
 is present or referenced. Please provide your references.
* [ ] The following questions are addressed in the documentation*:  Developers (what did you do?, how can it be maintained?), For users (how to use your work?), For admins (how to install and configure your work?)
* For documentation: Please write or update the Readme in the current working directory!

### Checks by code reviewer(s):
* [ ] Is the code clean of development artifacts e.g., unnecessary comments, prints, ...
* [ ] The ticket goals for each associated issue are reached or problems are clearly addressed (i.e., a new issue was introduced).
* [ ] There are appropriate **unit tests** and they pass.
* [ ] The git history is clean and linearized for the merge request.
* [ ] Coverage report for new code is acceptable. 

Closes #45

2022-05-05 14:48 UTC, xsaschako requested changes
Looks good, some minor changes which are grammar need to be corrected.

2022-05-10 07:33 UTC, dabele commented on pycode/memilio-simulation/memilio/simulation/abm.cpp
> +        .value("Age80plus", mio::AbmAgeGroup::Age80plus);
In python, the abm is already in its own module, so the `Abm` prefix is unnecessary. This will be changed in C++ as well, see #280 .

2022-05-10 07:34 UTC, dabele commented on pycode/memilio-simulation/memilio/simulation_test/test_abm.py
> +        home = world.locations[home_id.type][home_id.index]
removed

2022-05-10 07:34 UTC, dabele commented on cpp/models/abm/trip_list.cpp
> +    //same person can only make one trip at the same time
what do you mean by indentation? comments are on the same level as the code, as they should be

2022-05-10 07:35 UTC, dabele commented on cpp/models/abm/simulation.h
> +     * create a simulation with an empty world.
Fixed (along with all the other doc strings)

2022-05-10 14:09 UTC, xsaschako commented on cpp/models/abm/trip_list.cpp
> +    //same person can only make one trip at the same time
Meant punctuation, sorry.

2022-05-10 14:09 UTC, xsaschako commented on pycode/memilio-simulation/memilio/simulation/abm.cpp
> +PYBIND11_MODULE(_simulation_abm, m)
For example InfectionState is taken from state.h. 

So the comment would be '// Pythonbindings for state.h'.
That may be unneccessary though.

2022-05-10 15:16 UTC, dabele commented on pycode/memilio-simulation/memilio/simulation/abm.cpp
> +PYBIND11_MODULE(_simulation_abm, m)
This will resolve itself soon, we are currently working on improving the python binding file structure

2022-05-10 15:16 UTC, merged