251 add test set for divi data
DLR-SC/memilio pull request #259
Opened 2022-04-27 13:47 UTC by annette-lutz

## Merge Request - GuideLine Checklist 

**Guideline** to check code before resolve WIP and approval, respectively.
As many checkboxes as possible should be ticked.

### Checks by code author:
* [ ] There is at least one issue associated with the pull request.
* [ ] The branch follows the naming conventions as defined in the [git workflow](git-workflow).
* [ ] New code adheres with the [coding guidelines](coding-guidelines)
* [ ] Tests for new functionality has been added
* [ ] A local test was succesful
* [ ] There is appropriate **documentation** of your work. (use doxygen style comments)
* [ ] If new third party software is used, did you pay attention to its license? Please remember to add it to the wiki after successful merging.
* [ ] If new mathematical methods or epidemiological terms are used, has the glossary been updated ? Did you provide further documentation ?
 is present or referenced. Please provide your references.
* [ ] The following questions are addressed in the documentation*:  Developers (what did you do?, how can it be maintained?), For users (how to use your work?), For admins (how to install and configure your work?)
* For documentation: Please write or update the Readme in the current working directory!

### Checks by code reviewer(s):
* [ ] Is the code clean of development artifacts e.g., unnecessary comments, prints, ...
* [ ] The ticket goals for each associated issue are reached or problems are clearly addressed (i.e., a new issue was introduced).
* [ ] There are appropriate **unit tests** and they pass.
* [ ] The git history is clean and linearized for the merge request.
* [ ] Coverage report for new code is acceptable. 

Closes #251.

2022-05-04 11:02 UTC, patricklnz requested changes
Full review

2022-05-09 14:32 UTC, annette-lutz commented on pycode/memilio-epidata/memilio/epidata_test/test_epidata_get_divi_data.py
> +    def test_extracted_state_subframe(self):
I remove this test.

2022-05-09 14:32 UTC, annette-lutz commented on pycode/memilio-epidata/memilio/epidata_test/test_epidata_get_divi_data.py
> +        mock_san.assert_has_calls([call(self.df_test)])
This tests whether the `divi_data_sanity_checks` function which is mocked by `mock_san` is called with `self.df_test` as input.

2022-05-09 14:32 UTC, annette-lutz commented on pycode/memilio-epidata/memilio/epidata_test/test_epidata_get_divi_data.py
> +        mock_san.assert_has_calls([call(self.df_test)])
see above

2022-05-09 14:32 UTC, annette-lutz commented on pycode/memilio-epidata/memilio/epidata_test/test_epidata_get_divi_data.py
> +        mock_san.assert_has_calls([call(self.df_test)])
See answer below.

2022-05-09 14:32 UTC, annette-lutz commented on pycode/memilio-epidata/memilio/epidata_test/test_epidata_get_divi_data.py
> +        mock_san.assert_has_calls([call(self.df_test)])
see above

2022-05-09 14:32 UTC, annette-lutz commented on pycode/memilio-epidata/memilio/epidata_test/test_epidata_modifyDataframeSeries.py
> +        pd.testing.assert_frame_equal(self.df_dates, test_df)
If the dataframe is not copied but directly manipulated in the function `extract_subframe_based_on_dates`, this test fails.

2022-05-09 14:32 UTC, annette-lutz commented on pycode/memilio-epidata/memilio/epidata_test/test_epidata_modifyDataframeSeries.py
> +        pd.testing.assert_frame_equal(self.df_dates, test_df)
same as above

2022-05-11 10:37 UTC, patricklnz approved these changes
Looks good.

2022-05-11 10:37 UTC, merged