299 bind oseir model
DLR-SC/memilio pull request #307
Opened 2022-07-04 12:36 UTC by MaxBetzDLR

## Merge Request - GuideLine Checklist 

**Guideline** to check code before resolve WIP and approval, respectively.
As many checkboxes as possible should be ticked.

### Checks by code author:
* [x] There is at least one issue associated with the pull request.
* [x] The branch follows the naming conventions as defined in the [git workflow](git-workflow).
* [x] New code adheres with the [coding guidelines](coding-guidelines)
* [x] Tests for new functionality has been added
* [x] A local test was succesful
* [x] There is appropriate **documentation** of your work. (use doxygen style comments)
* [ ] If new third party software is used, did you pay attention to its license? Please remember to add it to the wiki after successful merging.
* [ ] If new mathematical methods or epidemiological terms are used, has the glossary been updated ? Did you provide further documentation ?
 is present or referenced. Please provide your references.
* [ ] The following questions are addressed in the documentation*:  Developers (what did you do?, how can it be maintained?), For users (how to use your work?), For admins (how to install and configure your work?)
* For documentation: Please write or update the Readme in the current working directory!

### Checks by code reviewer(s):
* [ ] Is the code clean of development artifacts e.g., unnecessary comments, prints, ...
* [ ] The ticket goals for each associated issue are reached or problems are clearly addressed (i.e., a new issue was introduced).
* [ ] There are appropriate **unit tests** and they pass.
* [ ] The git history is clean and linearized for the merge request.
* [ ] Coverage report for new code is acceptable. 

Closes #299

2022-07-04 14:55 UTC, dabele requested changes

2022-07-04 14:55 UTC, dabele commented on pycode/examples/simulation/oseir_simple.py
> +    arg_parser.add_argument('-p', '--show_plot', action='store_const', const=True, default=False)
I don't think you need this here.

2022-07-04 14:55 UTC, dabele commented on pycode/examples/simulation/oseir_simple.py
> +    """
I think this is copy paste from secir. Seir doesn't have age groups, and this example doesn't plot anything.

2022-07-04 14:55 UTC, dabele commented on pycode/examples/simulation/oseir_simple.py
> +    compartments = ['Susceptible', 'Exposed', 'Infected', 'Recovered']
unused

2022-07-04 14:55 UTC, dabele commented on pycode/examples/simulation/oseir_simple.py
> +    num_compartments = len(compartments)
unused

2022-07-04 14:55 UTC, dabele commented on pycode/memilio-simulation/memilio/simulation/oseir.cpp
> +#include <vector>
I don't think you are using either of these includes.

2022-07-05 07:23 UTC, MaxBetzDLR commented on pycode/memilio-simulation/memilio/simulation/utils/index.h
> +#include "memilio/utils/custom_index_array.h"
IndexPosition is used for casting which is defined in custom_index_array.h, so i thought it is required

2022-07-05 09:10 UTC, dabele commented on pycode/memilio-simulation/memilio/simulation/utils/index.h
> +#include "memilio/utils/custom_index_array.h"
Ok, I didn't see that. That's an issue in the c++ library then. It's also questionable to use something in a `details` namespace outside of the library itself. But you don't need to fix that right now.

2022-07-06 16:26 UTC, dabele approved these changes

2022-07-06 16:26 UTC, merged