Restructure IO for Graph-ODE and allow basic IO for ABM
DLR-SC/memilio pull request #449
Opened 2022-11-11 12:24 UTC by mknaranja

## Merge Request - GuideLine Checklist 

**Guideline** to check code before resolve WIP and approval, respectively.
As many checkboxes as possible should be ticked.

### Checks by code author:
* [ ] There is at least one issue associated with the pull request.
* [ ] The branch follows the naming conventions as defined in the [git workflow](git-workflow).
* [ ] New code adheres with the [coding guidelines](coding-guidelines)
* [ ] Tests for new functionality has been added
* [ ] A local test was succesful
* [ ] There is appropriate **documentation** of your work. (use doxygen style comments)
* [ ] If new third party software is used, did you pay attention to its license? Please remember to add it to the wiki after successful merging.
* [ ] If new mathematical methods or epidemiological terms are used, has the glossary been updated ? Did you provide further documentation ?
 is present or referenced. Please provide your references.
* [ ] The following questions are addressed in the documentation*:  Developers (what did you do?, how can it be maintained?), For users (how to use your work?), For admins (how to install and configure your work?)
* For documentation: Please write or update the Readme in the current working directory!

### Checks by code reviewer(s):
* [ ] Is the code clean of development artifacts e.g., unnecessary comments, prints, ...
* [ ] The ticket goals for each associated issue are reached or problems are clearly addressed (i.e., a new issue was introduced).
* [ ] There are appropriate **unit tests** and they pass.
* [ ] The git history is clean and linearized for the merge request.
* [ ] Coverage report for new code is acceptable. 

Closes #364 #446

2022-11-11 14:06 UTC, mknaranja commented on cpp/memilio/io/result_io.h
> +        }
@HenrZu Let's have a look on this on Monday. Isn't this actually already saved in the run function?

2022-11-11 15:35 UTC, mknaranja commented on cpp/memilio/io/result_io.h
> +IOResult<void> save_result_with_params(const std::vector<TimeSeries<double>>& result, const std::vector<Model>& params,
needs test

2022-11-11 15:35 UTC, mknaranja commented on cpp/memilio/io/result_io.h
> +IOResult<void> save_results(const std::vector<std::vector<TimeSeries<double>>>& ensemble_results,
needs test

2022-11-15 15:02 UTC, HenrZu requested changes

2022-11-15 15:02 UTC, HenrZu commented on cpp/simulations/2020_npis_sarscov2_wildtype_germany.cpp
> +        save_single_runs = argv[4];
Would be more consistent with the other simulation file

2022-11-16 10:31 UTC, HenrZu approved these changes
Looks good

2022-11-16 10:32 UTC, merged