418 Rework Test odesecirvvs export_time_series_init
DLR-SC/memilio pull request #497
Opened 2022-12-07 14:08 UTC by jubicker

## Merge Request - GuideLine Checklist 

**Guideline** to check code before resolve WIP and approval, respectively.
As many checkboxes as possible should be ticked.

### Checks by code author:
Always to be checked:
* [x] There is at least one issue associated with the pull request.
* [x] The branch follows the naming conventions as defined in the [git workflow](git-workflow).
* [x] New code adheres with the [coding guidelines](coding-guidelines)
* [ ] Make sure that the [pre-commit linting/style checks pass](https://github.com/DLR-SC/memilio/wiki).

If functions were changed or functionality was added:
* [x] Tests for new functionality has been added
* [x] A local test was succesful

If new functionality was added:
* [ ] There is appropriate **documentation** of your work. (use doxygen style comments)

If new third party software is used:
* [ ] Did you pay attention to its license? Please remember to add it to the wiki after successful merging.

If new mathematical methods or epidemiological terms are used:
* [ ] Are new methods referenced? Did you provide further documentation? Has the glossary been updated? 

The following questions are addressed in the documentation if need be: 
* [ ] Developers (what did you do?, how can it be maintained?)
* [ ] For users (how to use your work?)
* [ ] For admins (how to install and configure your work?)

* For documentation: Please write or update the Readme in the current working directory!

### Checks by code reviewer(s):
* [x] Is the code clean of development artifacts e.g., unnecessary comments, prints, ...
* [x] The ticket goals for each associated issue are reached or problems are clearly addressed (i.e., a new issue was introduced).
* [x] There are appropriate **unit tests** and they pass.
* [x] The git history is clean and linearized for the merge request. All reviewers should squash commits and write a simple and meaningful commit message.
* [x] Coverage report for new code is acceptable.

2022-12-08 07:40 UTC, jubicker commented
Closes #418

2023-01-02 16:01 UTC, mknaranja requested changes

2023-01-02 16:04 UTC, mknaranja commented on cpp/tests/test_odesecirvvs.cpp
> +        mio::read_result(mio::path_join(TEST_DATA_DIR, "export_time_series_init_osecirvvs_with_vaccination.h5")).value();
If the old file is not used anymore, the new file should replace the old one and not be added additionally. The question is if or why we do not need to change the values in model_initialization

2023-01-04 08:02 UTC, mknaranja approved these changes

2023-01-04 08:03 UTC, merged