476 create geography subfolder in memilio and create graph for germany
DLR-SC/memilio pull request #526
Opened 2023-01-12 12:10 UTC by jubicker

## Merge Request - GuideLine Checklist 

**Guideline** to check code before resolve WIP and approval, respectively.
As many checkboxes as possible should be ticked.

### Checks by code author:
Always to be checked:
* [ ] There is at least one issue associated with the pull request.
* [ ] The branch follows the naming conventions as defined in the [git workflow](git-workflow).
* [ ] New code adheres with the [coding guidelines](coding-guidelines)
* [ ] Make sure that the [pre-commit linting/style checks pass](https://github.com/DLR-SC/memilio/wiki).

If functions were changed or functionality was added:
* [ ] Tests for new functionality has been added
* [ ] A local test was succesful

If new functionality was added:
* [ ] There is appropriate **documentation** of your work. (use doxygen style comments)

If new third party software is used:
* [ ] Did you pay attention to its license? Please remember to add it to the wiki after successful merging.

If new mathematical methods or epidemiological terms are used:
* [ ] Are new methods referenced? Did you provide further documentation? Has the glossary been updated? 

The following questions are addressed in the documentation if need be: 
* [ ] Developers (what did you do?, how can it be maintained?)
* [ ] For users (how to use your work?)
* [ ] For admins (how to install and configure your work?)

* For documentation: Please write or update the Readme in the current working directory!

### Checks by code reviewer(s):
* [ ] Is the code clean of development artifacts e.g., unnecessary comments, prints, ...
* [ ] The ticket goals for each associated issue are reached or problems are clearly addressed (i.e., a new issue was introduced).
* [ ] There are appropriate **unit tests** and they pass.
* [ ] The git history is clean and linearized for the merge request. All reviewers should squash commits and write a simple and meaningful commit message.
* [ ] Coverage report for new code is acceptable.

2023-01-18 10:52 UTC, HenrZu requested changes
Looks good. Only some short comments.
Also, you should link the Issue with the PR :)

2023-01-18 10:52 UTC, HenrZu commented on cpp/simulations/2021_vaccination_sarscov2_delta_germany.cpp
> +    const auto num_days_sim = 20.0;
```suggestion
    const auto num_days_sim = 90.0;
```

I think you changed the values for testing :)

2023-01-18 10:52 UTC, HenrZu commented on cpp/simulations/2021_vaccination_sarscov2_delta_germany.cpp
> +    const auto num_runs     = 1;
```suggestion
    const auto num_runs     = 500;
```

2023-01-18 15:00 UTC, jubicker commented on cpp/simulations/2020_npis_sarscov2_wildtype_germany.cpp
> +    BOOST_OUTCOME_TRY(create_graph_function(params_graph, params, start_date, end_date, data_dir, read_function,
Yes they are set by default, but however there arises an error when trying to build without setting the last two input arguments

2023-01-19 07:29 UTC, jubicker commented
closes #476

2023-01-23 12:47 UTC, HenrZu approved these changes

2023-01-26 07:15 UTC, jubicker commented
@HenrZu @mknaranja I moved the functions from epi_data.h to graph.h. Can you have another look at it?

2023-02-08 09:21 UTC, HenrZu requested changes
Looks good 👍

2023-02-08 09:21 UTC, HenrZu commented on cpp/memilio/geography/regions.h
> +
```suggestion
```

delete this space

2023-02-08 09:21 UTC, HenrZu commented on cpp/memilio/io/epi_data.h
> +        auto state_id                   = obj.expect_optional("ID_County", Tag<regions::StateId>{});
```suggestion
        auto state_id                   = obj.expect_optional("ID_State", Tag<regions::StateId>{});
```

2023-02-08 09:21 UTC, HenrZu commented on cpp/memilio/mobility/graph.h
> +template <class TestNTrace, class ContactPattern, class Model, class MigrationParams, class Parameters,
```suggestion
template <class TestAndTrace, class ContactPattern, class Model, class MigrationParams, class Parameters,
```

2023-02-08 09:21 UTC, HenrZu commented on cpp/memilio/mobility/graph.h
> +        auto& tnt_value = counties[county_idx].parameters.template get<TestNTrace>();
```suggestion
        auto& tnt_value = counties[county_idx].parameters.template get<TestAndTrace>();
```

2023-02-08 09:21 UTC, HenrZu commented on cpp/models/ode_secir/parameters_io.h
> + * @param num_days Number of days to be simulated; required to extrapolate real data
```suggestion
 * @param num_days [Default: 0] Number of days to be simulated; required to extrapolate real data
```

2023-02-08 09:21 UTC, HenrZu commented on cpp/models/ode_secir/parameters_io.h
> + * @param export_time_series If true, reads data for each day of simulation and writes it in the same directory as the input files.
```suggestion
 * @param export_time_series [Default: false] If true, reads data for each day of simulation and writes it in the same directory as the input files.
```

2023-02-08 10:28 UTC, HenrZu approved these changes
Thanks. As discussed, the code coverage will be improved in issue #525.

2023-02-08 10:30 UTC, merged