WIP: 626 upgrade to python 11
DLR-SC/memilio pull request #682
Opened 2023-06-30 10:47 UTC by MaxBetzDLR

## Changes

Please briefly list the changes made:

[Describe here in 2-3 lines. For details, reference to issues to avoid redundant information.]

## Merge Request - GuideLine Checklist

- *Check our [git workflow](https://github.com/DLR-SC/memilio/wiki/git-workflow) before opening a Pull request/Merge request.*
- *Request a reviewer when your work is ready to review, before this please use the draft feature.*

### Checks by code author

- [ ] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [ ] New code adheres to [coding guidelines](https://github.com/DLR-SC/memilio/wiki/Coding-guidelines)
- [ ] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] Tests are added for new functionality and a local test run was successful
- [ ] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [ ] Proper attention to licenses, especially no new third-party software with conflicting license has been added

### Checks by code reviewer(s)

- [ ] Corresponding issue(s) is/are linked and addressed
- [ ] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [ ] Appropriate **unit tests** have been added, CI passes and code coverage is acceptable (did not decrease)
- [ ] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)

### Additional context

Please list additional information or things a reviewer should look out for.

Closes #626

2023-07-17 07:12 UTC, patricklnz requested changes
The epidata test for hospilization data fails with a RecursionError, this has to be fixed. Also some comments on why we use specific versions. Else looks good to me.

2023-07-17 07:12 UTC, patricklnz commented on pycode/memilio-epidata/requirements-dev.txt
> +pylint_json2html==0.4.0
Update comments why we use this versions

2023-07-17 07:12 UTC, patricklnz commented on pycode/memilio-epidata/setup.py
> +            'pylint_json2html==0.4.0',
Comments should be the same as in requirements-dev.txt

2023-07-17 07:12 UTC, patricklnz commented on pycode/memilio-plot/requirements-dev.txt
> +pylint_json2html==0.4.0
see above

2023-07-17 07:12 UTC, patricklnz commented on pycode/memilio-plot/setup.py
> +            'pylint_json2html==0.4.0',
see above

2023-07-25 07:11 UTC, dabele commented
pybind was upgraded here: #705

2023-08-01 09:11 UTC, patricklnz approved these changes
Looks good to me.

2023-08-01 11:40 UTC, mknaranja commented on pycode/memilio-generation/memilio/generation/utility.py
> +    # For python 3.8 and newer
```suggestion
    # For python 3.9 and newer
```
?

2023-08-01 11:43 UTC, mknaranja approved these changes

2023-08-01 17:26 UTC, mknaranja commented
Thank you @MaxBetzDLR and @patricklnz. Good work!

2023-08-01 17:27 UTC, merged