766 implementation of ode sir model
DLR-SC/memilio pull request #775
Opened 2023-09-21 09:39 UTC by alexgit0

# Changes and Information

- Implementation of SIR model and corresponding python bindings 

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/DLR-SC/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [ ] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [ ] New code adheres to [coding guidelines](https://github.com/DLR-SC/memilio/wiki/Coding-guidelines)
- [ ] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] Tests are added for new functionality and a local test run was successful
- [ ] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [ ] Proper attention to licenses, especially no new third-party software with conflicting license has been added

### Checks by code reviewer(s)

- [ ] Corresponding issue(s) is/are linked and addressed
- [ ] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [ ] Appropriate **unit tests** have been added, CI passes and code coverage is acceptable (did not decrease)
- [ ] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)

closes #766

2023-09-28 08:26 UTC, MaxBetzDLR requested changes

2023-09-28 08:26 UTC, MaxBetzDLR commented on cpp/models/ode_sir/parameters.h
> + * @brief Parameters of an age-resolved SECIR/SECIHURD model.
Wrong model in brief

2023-09-28 08:26 UTC, MaxBetzDLR commented on cpp/models/ode_sir/parameters.h
> +
Copyright header missing

2023-09-28 08:26 UTC, MaxBetzDLR commented on cpp/models/ode_sir/model.h
> +
Copyright header

2023-09-28 08:26 UTC, MaxBetzDLR commented on cpp/models/ode_sir/model.cpp
> +
Copyright header

2023-09-28 08:26 UTC, MaxBetzDLR commented on cpp/models/ode_sir/infection_state.h
> +
Copyright header

2023-09-28 08:26 UTC, MaxBetzDLR commented on cpp/examples/ode_sir.cpp
> +
copyright header missing. You can use the one from ode_seir/model.cpp

2023-09-28 08:26 UTC, MaxBetzDLR commented on cpp/tests/data/sir-js-compare.csv
Prefix ode should be added, as in the file name ide-seir-compare.csv

2023-09-28 08:26 UTC, MaxBetzDLR commented on pycode/examples/simulation/osir_simple.py
> +# Copyright (C) 2020-2021 German Aerospace Center (DLR-SC)
```suggestion
# Copyright (C) 2020-2023 German Aerospace Center (DLR-SC)
```

2023-09-28 08:26 UTC, MaxBetzDLR commented on pycode/memilio-simulation/memilio/simulation/osir.cpp
> +
Copyright header

2023-09-28 08:26 UTC, MaxBetzDLR commented on pycode/memilio-simulation/memilio/simulation/osir.py
> +# Copyright (C) 2020-2021 German Aerospace Center (DLR-SC)
```suggestion
# Copyright (C) 2020-2023 German Aerospace Center (DLR-SC)
```

2023-09-28 08:26 UTC, MaxBetzDLR commented on pycode/memilio-simulation/memilio/simulation_test/test_osir.py
> +# Copyright (C) 2020-2021 German Aerospace Center (DLR-SC)
```suggestion
# Copyright (C) 2020-2023 German Aerospace Center (DLR-SC)
```

2023-09-28 13:29 UTC, alexgit0 commented on cpp/tests/data/sir-js-compare.csv
prefix will be added, however there is no prefix for seir-js-compare.csv either

2023-09-29 13:03 UTC, MaxBetzDLR commented on cpp/tests/data/sir-js-compare.csv
Your right, if possible change it aswell

2023-09-29 13:15 UTC, mknaranja commented on cpp/examples/ode_sir.cpp
> +    // params.nb_sus_t0   = params.nb_total_t0 - params.nb_exp_t0 - params.nb_inf_t0 - params.nb_rec_t0;
exposed does not exist here

2023-09-29 13:15 UTC, mknaranja commented on cpp/examples/ode_sir.cpp
> +    // print_seir_params(model);
pls remove development artifacts

2023-09-29 13:16 UTC, mknaranja commented on cpp/models/ode_sir/infection_state.h
Please use `Recovered` as in SEIR.

2023-09-29 13:18 UTC, mknaranja commented on cpp/models/ode_sir/model.h
> +            -coeffStoE * y[(size_t)InfectionState::Susceptible] * pop[(size_t)InfectionState::Infected];
The variable should be `coeffStoI` now.

Please think of adapting related comments and variable names too when changing the model.

2023-09-29 13:20 UTC, mknaranja commented on cpp/tests/data/ode-sir-js-compare.csv
> + # t S I R
Although it is not 100kb, 40kb is still large for a file like this. You probably adapted well from the old file but we should stick to smaller files as the repo grows. I think comparing the first 20 steps is already sufficient to compare the results to some higher accuracy. If there is an imprecision of X after 100 iterations, there is an imprecision of Y after 10 iterations.

2023-10-05 07:53 UTC, MaxBetzDLR commented on cpp/models/ode_sir/README.md
> +- Recovered, recovered from infectious process (dead or recovered).
```suggestion
- Recovered, recovered from infectious process (dead or recovered)

```

2023-10-05 09:08 UTC, HenrZu approved these changes

2023-10-05 09:15 UTC, MaxBetzDLR approved these changes

2023-10-05 09:16 UTC, merged

2023-10-05 09:18 UTC, mknaranja requested changes

2023-10-05 09:18 UTC, mknaranja commented on cpp/models/ode_sir/infection_state.h
> +#define SIR_INFECTIONSTATE_H
```suggestion
#ifndef ODESIR_INFECTIONSTATE_H
#define ODESIR_INFECTIONSTATE_H
```

2023-10-05 09:18 UTC, mknaranja commented on cpp/models/ode_sir/infection_state.h
> +#endif // SIR_INFECTIONSTATE_H
```suggestion
#endif // ODESIR_INFECTIONSTATE_H
```

2023-10-05 09:18 UTC, mknaranja commented on cpp/models/ode_sir/model.h
> +#define SIR_MODEL_H
```suggestion
#ifndef ODESIR_MODEL_H
#define ODESIR_MODEL_H
```

2023-10-05 09:18 UTC, mknaranja commented on cpp/models/ode_sir/model.h
> +#endif // SIR_MODEL_H
```suggestion
#endif // ODESIR_MODEL_H
```