537 silence gmock warnings
DLR-SC/memilio pull request #801
Opened 2023-10-13 16:28 UTC by dabele

# Changes and Information

Silence some gmock warnings in a unit test by using NiceMock. The default implementation for `get_result` of the Mock class does the right thing, so silencing the warning is OK. 

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/DLR-SC/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [x] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [x] New code adheres to [coding guidelines](https://github.com/DLR-SC/memilio/wiki/Coding-guidelines)
- [x] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [x] Tests are added for new functionality and a local test run was successful
- [x] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [x] Proper attention to licenses, especially no new third-party software with conflicting license has been added

### Checks by code reviewer(s)

- [ ] Corresponding issue(s) is/are linked and addressed
- [ ] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [ ] Appropriate **unit tests** have been added, CI passes and code coverage is acceptable (did not decrease)
- [ ] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)

2023-10-16 13:36 UTC, xsaschako approved these changes
nicemock makes sense here, thanks, although codecov fails, so this isn't mergable!

2023-10-16 13:38 UTC, xsaschako requested changes
nicemock makes sense here,although this leads to a function not being called in timeseries. This currently needs to be fixed for a merge

2023-10-20 09:23 UTC, dabele commented
I added a basic test for the PrintTo function. I wouldn't want the test to in any way restrict what the output should be like or be difficult to maintain, so it basically just tests that the function exists and does something.

2023-10-20 10:12 UTC, xsaschako approved these changes
Makes sense and looks good, thank you.

2023-10-20 10:12 UTC, merged